Distance
CodeTheDream/ride-share-app pull request #106
Opened 2021-01-15 22:11 UTC by elizy88

2021-01-19 17:58 UTC, elizy88 commented
![appdistance requested ride](https://user-images.githubusercontent.com/35976784/105074059-e2e04280-5a55-11eb-85ea-87aa1495b635.JPG)
![Approximate distance](https://user-images.githubusercontent.com/35976784/105074101-f095c800-5a55-11eb-84c6-134310473584.jpg)

2021-01-19 18:10 UTC, elizy88 commented
![App Distance](https://user-images.githubusercontent.com/35976784/105075344-a6154b00-5a57-11eb-97ac-d507cb8c4ccd.JPG)

2021-01-21 20:21 UTC, kidatsy requested changes

2021-01-21 20:21 UTC, kidatsy commented on app/components/Card/UpcomingRideCard/UpcomingRideCard.js
> +
That's a lot of white space!

2021-01-21 20:21 UTC, kidatsy commented on app/components/Card/UpcomingRideCard/UpcomingRideCard.js
> +
Ditto on white space

2021-01-21 20:21 UTC, kidatsy commented on app/components/Card/UpcomingRideCard/UpcomingRideCard.js
> +        </TouchableOpacity>
Can you standardize the indentation/spaces on these rows so that it's more readable?

2021-01-21 20:21 UTC, kidatsy commented on app/components/Card/RequestRidesCard/RequestedRidesCard.js
> +        </TouchableOpacity>
I have a feeling you can probably abstract the distance stuff here out to its own component, which you can then use both here in `RequestedRidesCard` and `UpcomingRideCard`. There might be some differences, which you can address by passing different props, depending on where you're including the component.

2021-01-21 20:21 UTC, kidatsy commented on app/components/Card/RequestRidesCard/RequestedRidesCard.js
> +        </TouchableOpacity>
That would then set you up pretty nicely for the next card, consolidating the pickup/dropoff and distance blocks.

2021-01-21 21:25 UTC, elizy88 commented on app/components/Card/UpcomingRideCard/UpcomingRideCard.js
> +        </TouchableOpacity>
I used prettier to format the document and now it is good to go

2021-01-21 21:28 UTC, elizy88 commented on app/components/Card/UpcomingRideCard/UpcomingRideCard.js
> +
Removed white spaces

2021-02-02 20:49 UTC, closed without merging