First name last initial
CodeTheDream/ride-share-app pull request #109
Opened 2021-01-22 23:52 UTC by NiDaSanti

2021-01-25 16:46 UTC, NiDaSanti commented
![Screen Shot 2021-01-25 at 8 46 14 AM](https://user-images.githubusercontent.com/45866637/105736568-ccb90300-5ee9-11eb-8d6d-b9f171e0bc86.png)

2021-01-25 17:02 UTC, kidatsy commented on app/components/Card/RequestRidesCard/RequestedRidesCard.js
> +          {riderInfo.last_name + ', ' + initials}
Would it make sense to just extract the initials and concatenate the whole thing in this component, instead of sending them separately from the `riderInfo`, since they're being pulled from `riderInfo.first_name` anyway?

2021-01-25 17:02 UTC, kidatsy commented on app/views/MainView/MainView.js
> +        initials={initials}
That way, you'd only have to pass in `riderInfo` here.

2021-01-25 17:08 UTC, NiDaSanti commented on app/components/Card/RequestRidesCard/RequestedRidesCard.js
> +          {riderInfo.last_name + ', ' + initials}
For sure I can try that TC.

2021-01-25 17:08 UTC, NiDaSanti commented on app/views/MainView/MainView.js
> +        initials={initials}
Pass in concat value here right?

2021-01-27 06:28 UTC, NiDaSanti commented
in this commit I created an array called riderNameAndLast. I split the first item in the array and kept the last_name as is. Since the array is in order by first name and last name, I used reverse method to switch the array items and I called that variable rerverseName. Then, I created a variable joinedRiderNameAndLast = reverseName.join(', '), however I feel like I could add the join() method when referencing joinedRiderNameAndLast. In all I feel like the objective is completed. Let me know.

2021-01-27 06:29 UTC, NiDaSanti commented
![Screen Shot 2021-01-26 at 10 29 36 PM](https://user-images.githubusercontent.com/45866637/105952126-fb3bf880-6025-11eb-91f2-bc235b616bc5.png)

2021-01-27 19:22 UTC, kidatsy requested changes

2021-01-27 19:22 UTC, kidatsy commented on app/views/MainView/MainView.js
> +    const joinedRiderNameAndLast = reverseName.join(', ');
Thanks for doing all that work in one place! I'm not sure if it makes more sense to do it here or in `Requested RidesCard`, but either way, it's good to have it in one place. It looks like you're doing
```
Last, F.
```
instead of
```
First L.
```
which is what the ticket called for. I feel like giving the first name would help the driver create a friendlier environment. Would you mind switching it around?

2021-01-27 19:22 UTC, kidatsy commented on app/views/MainView/MainView.js
> +    const joinedRiderNameAndLast = reverseName.join(', ');
I do appreciate the usage of array functions here.
You could probably just do `const riderName = [item.rider.first_name, item.rider.last_name.split('', 1)].join(' ');` or something a bit more broken down into steps.

Oh, I also see that we're already sending the `name` prop, which is currently set to `item.riderName`. How are we currently using that in the child component? It would be great if we could limit it down to one or the other.

2021-01-27 19:22 UTC, kidatsy commented on app/views/MainView/MainView.js
>      date.toString();
Also, this `requestedRide` function feels like it wants to pop off to be its own, independent functional component, complete with props, etc. instead of just being a function within `MainView`. Now that I look at the file, there's a bunch of other functions like this in there. I know this is outside the scope of the ticket, but it would be great if we could start refactoring them off into their own components.

2021-01-27 20:01 UTC, NiDaSanti commented on app/views/MainView/MainView.js
> +    const joinedRiderNameAndLast = reverseName.join(', ');
I agree TC, I asked Narayan about it  but i think he saw it from a business perspective and I respected his request, but I will change it.

2021-01-27 20:07 UTC, NiDaSanti commented on app/views/MainView/MainView.js
> +    const joinedRiderNameAndLast = reverseName.join(', ');
you just thought me a new technique thanks!

2021-01-27 22:14 UTC, NiDaSanti commented on app/views/MainView/MainView.js
> +    const joinedRiderNameAndLast = reverseName.join(', ');
changed the order of the name to first name and last initial. The name prop I ignored initially, but when I checked it had a value of undefined, so I deleted it. If I'm not mistaken it's in other parts of the file. I also was looking at the what you mentioned on the functions and how you'd want us to refactor the code. My question is do you want us too refactor as we complete objectives or will we look into everything we should refactor as a group.

2021-01-28 17:42 UTC, kidatsy commented on app/views/MainView/MainView.js
>      date.toString();
Good question about scope, Nick. I've made a separate task ticket to do this kind of clean-up: https://codethedream.atlassian.net/browse/CR-108

2021-01-28 17:42 UTC, kidatsy approved these changes
LGTM

2021-01-29 17:29 UTC, merged