removed the ride complete button
CodeTheDream/ride-share-app pull request #112
Opened 2021-02-12 16:18 UTC by jwpeterkim

## Description

What does the PR do?
Removes the unnecessary complete button in the RideView page.

## Background Information
Complete ride button is redundant since dropping off the rider automatically completes the ride and we don't want to say the ride is completed unless the rider is dropped off.

## Screenshots
![Screen Shot 2021-02-11 at 23 43 56](https://user-images.githubusercontent.com/63831504/107792843-36734280-6d1b-11eb-9188-ca1c443219fa.png)

## Checklist:
- [v] Screenshots attached (if dealing with UI)
- [ ] Unit Tests (if applicable)

## Testing Steps for reviewer:
- Step 1 
Go to RideView.js and see the lines 269-289 and 554-560 being commented out. 
- Step 2
Check if the modal doesn't show the complete ride button on your simulator. (it should now show only the ride cancel button.)

2021-02-17 16:57 UTC, kidatsy requested changes
Just cut the code out, instead of commenting!

2021-02-17 16:57 UTC, kidatsy commented on app/views/RideView/RideView.js
> +  // };
Just 🪓 this all!

2021-02-17 16:57 UTC, kidatsy commented on app/views/RideView/RideView.js
> +                    /> */}
✂️

2021-02-18 15:22 UTC, jwpeterkim commented
> Just cut the code out, instead of commenting!

Me and Elsa just weren't sure if we'd be needing or referencing some of "the complete ride button" codes in the future. Especially since it looked like there were lots of work put into it. But if you can confirm we won't need them, I can definitely just remove them and resubmit it! Let me know what you think!

2021-02-18 20:54 UTC, jwpeterkim commented
Hi TC, I removed unnecessary lines as we discussed. It should be good to go!
Let me know if there are any other issues with this PR. Thanks!

2021-02-19 16:26 UTC, kidatsy approved these changes
LGTM!

2021-02-19 16:26 UTC, merged