Readme
CodeTheDream/ride-share-app pull request #113
Opened 2021-02-20 20:11 UTC by elizy88

## Description
Modified the Readme to have a descriptive installation process for Windows.

What does the PR do?
The PR  explains the process of setting the environment for windows OS users or for people who use MAC but want to use Android Studio

2021-02-24 21:14 UTC, kidatsy requested changes
README stuff looks fine, but there are a couple issues here:
1. What's going on with all those empty icon font files?
2. It's also including your work on the ticket Nick has now, with the rides outside of the user's availability.

2021-02-24 21:14 UTC, kidatsy commented on app/views/MainView/MainView.js
> +          data={outsideAvailRides}
@elizy88 it looks like your previous work on the rides outside of the user's availabilty got included in this PR. Can you make sure it's just the README stuff in this one?

2021-03-01 17:05 UTC, elizy88 commented on app/views/MainView/MainView.js
> +          data={outsideAvailRides}
I have modified the Readme file by adding files for x code installation in Mac , and also I removed the changes I had for the outside my availablity codes.
but I am not clear  about this 
"What's going on with all those empty icon font files?"

2021-03-05 17:52 UTC, kidatsy commented on app/views/MainView/MainView.js
> +          data={outsideAvailRides}
It looks like these files got emptied out somehow 
![Screen Shot 2021-03-05 at 9 51 47 AM](https://user-images.githubusercontent.com/2397451/110153871-723c7d80-7d98-11eb-84c1-b678fdd0cc39.png)

2021-03-09 13:51 UTC, elizy88 commented on app/views/MainView/MainView.js
> +          data={outsideAvailRides}
@kidatsy  It seems that the assets folder was missing so I have added the assets folder and the subfolder fonts.

2021-03-09 15:21 UTC, kidatsy approved these changes
LGTM

2021-03-09 15:22 UTC, kidatsy commented on README.md
> +- brew install node
I would consider installing something like `nodenv`, which will allow you to switch between different versions of node: https://github.com/nodenv/nodenv

2021-03-10 15:32 UTC, merged