removed the insurance start and end date requirement from the page.
CodeTheDream/ride-share-app pull request #114
Opened 2021-02-23 23:15 UTC by jwpeterkim

## Description

This PR removes the previously required insurance start and end dates from the vehicle registration form.

## Background Information

The information currently isn't required by Seymour Center.

## Screenshots
![Screen Shot 2021-02-23 at 16 59 08](https://user-images.githubusercontent.com/63831504/108920548-70392880-75fa-11eb-9444-7aec54ed4e85.png)

## Checklist:
- [v] Screenshots attached (if dealing with UI)
- [v] Unit Tests (if applicable)

## Testing Steps for reviewer:
- Step 1
See there are no insurance dates requirements in the vehicle information page or registration page.

2021-02-23 23:17 UTC, jwpeterkim commented
Currently, Osbaldo is working on adding another field to this page so we are unable to register/edit new vehicles. But I was able to check if the new PR request isn't causing any issues by using Swagger and it should be fine! (but as we discussed, we can also quickly review the page once Osblado completes his ticket as well!) Thanks!

2021-02-24 21:15 UTC, kidatsy requested changes
Same thing @jwpeterkim, just cut the code! We can always revert the commit if need be.

2021-02-24 21:30 UTC, jwpeterkim commented
> Same thing @jwpeterkim, just cut the code! We can always revert the commit if need be.

Oops! It was a mistake this time! Sorry!

2021-03-05 17:53 UTC, kidatsy approved these changes

2021-03-05 17:53 UTC, merged