Load welcome
CodeTheDream/ride-share-app pull request #117
Opened 2021-03-02 21:56 UTC by NiDaSanti

## Description
THIS PR IS RESPONSIBLE FOR ADDRESSING THE ISSUE IN THE WELCOME SCREEN. IF NO RIDES WERE REQUESTED, THEN THE SCREEN LOADS FOREVER.
What does the PR do?
THIS PR ADDRESSES THE WELCOME SCREEN FOREVER AND IT NEEDS ADDITIONAL TESTING FROM OTHER DEVELOPER TO ENSURE THE SOLUTIONS IMPLEMENTED WORK AS INTENDED.
## Background Information

## Screenshots
![Capture1](https://user-images.githubusercontent.com/45866637/109720526-10dd9a00-7b5f-11eb-94c4-fd4f7f9ff9ae.JPG)
![Screen Shot 2021-01-26 at 6 53 38 PM](https://user-images.githubusercontent.com/45866637/109720528-11763080-7b5f-11eb-86a1-74ad1829cbf8.png)
![Screen Shot 2021-01-26 at 6 52 45 PM](https://user-images.githubusercontent.com/45866637/109720529-120ec700-7b5f-11eb-96a0-c6079b5ea3ee.png)
![Screen Shot 2021-01-26 at 6 52 22 PM](https://user-images.githubusercontent.com/45866637/109720531-12a75d80-7b5f-11eb-95a9-3b0a3c75fcf5.png)
![Screen Shot 2021-01-26 at 6 49 19 PM](https://user-images.githubusercontent.com/45866637/109720532-12a75d80-7b5f-11eb-9f0d-471c0e35796e.png)
![Screen Shot 2021-01-26 at 6 45 40 PM](https://user-images.githubusercontent.com/45866637/109720538-13d88a80-7b5f-11eb-846d-0a6f2822b9d6.png)
![Screen Shot 2021-01-26 at 6 41 39 PM](https://user-images.githubusercontent.com/45866637/109720539-13d88a80-7b5f-11eb-9051-b6f1db5673d3.png)
![Screen Shot 2021-01-25 at 6 32 51 PM](https://user-images.githubusercontent.com/45866637/109720541-14712100-7b5f-11eb-9ee2-a09a167d49fe.png)
![Screen Shot 2021-01-25 at 11 12 12 AM](https://user-images.githubusercontent.com/45866637/109720542-14712100-7b5f-11eb-830a-d49fcf67ac23.png)

## Checklist:
- [ ] Screenshots attached (if dealing with UI)
- [ ] Unit Tests (if applicable)

## Testing Steps for reviewer:
- Step 1
- Step 2

2021-03-05 18:05 UTC, kidatsy requested changes
Please remember to remove all uses of `console.log` that don't have to do with error logging. Even in those cases, we should actually be sending them to some kind of error logging solution, but I don't think we have anything like that set up right now, so it's kind of a pass. But anything that we've put in for temporary development reasons should be taken out before merging to master

2021-03-05 18:05 UTC, kidatsy commented on app/views/MainView/MainView.js
> +                console.log('all rides: ', result);
`console.log`

2021-03-05 18:05 UTC, kidatsy commented on app/views/MainView/MainView.js
> +	console.log('check for ', numRides);
`console.log`s

2021-03-05 18:05 UTC, kidatsy commented on app/views/MainView/MainView.js
> +                const rides = result.rides || [];
I guess this works for now. Ideally, it would be great if we can abstract this API fetch stuff off to a utility somewhere else, where we can handle cases of empty data like this.

2021-03-08 17:26 UTC, NiDaSanti commented on app/views/MainView/MainView.js
> +                console.log('all rides: ', result);
thanks TC, it was removed.

2021-03-09 15:30 UTC, kidatsy commented on app/views/MainView/MainView.js
> +    console.log('render upcomming', scheduledRides);
🔪

2021-03-09 15:31 UTC, kidatsy commented
Just a couple more `console.log`s to remove, and it looks like there's a merge conflict from master to address, then we're done here!

2021-03-11 15:59 UTC, kidatsy approved these changes
I went ahead an removed all of the remaining unnecessary `console.log`s in this file, on top of fixing the merge conflict. There were a bunch!

2021-03-11 16:20 UTC, merged